name: cd-laravel-base
recipe: laravel
config:
  webroot: ./public
  php: 8.5
  database: mysql:8.4
  cache: none
  composer_version: 2-latest

services:
  appserver:
    run:
      - composer setup
  node:
    type: node:24
    build:
      - npm install
    run:
      - npm run build

tooling:
  npm:
    service: node
